CREATE TABLE `big_samll_data` (
  `big_samll_data_id` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '自增',
  `match_id` bigint(64) NOT NULL COMMENT '比赛id',
  `league_name_simply` varchar(64) DEFAULT NULL COMMENT '联赛名称',
  `host_name` varchar(64) DEFAULT NULL COMMENT '主队',
  `guest_name` varchar(54) DEFAULT NULL COMMENT '客队',
  `match_time` datetime DEFAULT NULL COMMENT '比赛时间',
  `host_goal` int(4) DEFAULT NULL COMMENT '主队得分',
  `guest_goal` int(4) DEFAULT NULL COMMENT '客队得分',
  `total_goal` int(4) DEFAULT NULL COMMENT '总得分',
  `game_result` int(4) DEFAULT NULL COMMENT '赛果，1主胜2平局3客胜',
  `company_name` varchar(64) DEFAULT NULL COMMENT '公司名称',
  `first_let_big_small` decimal(8,2) DEFAULT NULL COMMENT '初始大小球',
  `first_big` decimal(8,2) DEFAULT NULL COMMENT '初始大球赔率',
  `first_small` decimal(8,2) DEFAULT NULL COMMENT '初始小球赔率',
  `let_big_small` decimal(8,2) DEFAULT NULL COMMENT '大小球',
  `big` decimal(8,2) DEFAULT NULL COMMENT '大球赔率',
  `small` decimal(8,2) DEFAULT NULL COMMENT '小球赔率',
  `buy_big` decimal(8,2) DEFAULT NULL COMMENT '买大球结果',
  `buy_small` decimal(8,2) DEFAULT NULL COMMENT '买小球结果',
  `big_small_pre` int(4) DEFAULT NULL COMMENT '规律预测 大球-1 小球-2',
  `buy_result` decimal(8,2) DEFAULT NULL COMMENT '购买结果',
	`gmt_create` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  PRIMARY KEY (`big_samll_data_id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='大小球数据';